name: CD workflow for deploying models

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'K8S Namespace'
        type: string
        required: true
    push:
#      tags:
#        - "*#dev*"
      branch:
        - "dev-*"
jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/mlem-deploy.yaml
    with:
      namespace: ${{ github.event.inputs.namespace }}
    secrets: inherit
