name: MLEM deploy

on:
  workflow_call:
    inputs:
      namespace:
        description: 'K8S Namespace'
        type: environment
        required: true

jobs:
  rerun-pipeline:
    runs-on: ubuntu-latest
    environment: cloud
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      # This block is using Iterative Sandbox AWS User
      # Comment it out if using your own credentials
#      - uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-region: us-east-1
#          role-to-assume: arn:aws:iam::342840881361:role/SandboxUser
      - name: Setup Git User
        run: cml ci
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Deploy to Heroku with MLEM
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: |
           echo "===========NAMESPACE============"
           echo ${{ github.event.inputs.namespace }}
#          pip install -r requirements.txt
#          dvc pull .mlem/model/clf-model
#          mlem deployment run api-customer-churn-dev
